/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUII.PANEL;

import PALETTE.SlidingStatusToogle;
import java.awt.event.ActionEvent;
import java.util.prefs.Preferences;
/**
 *
 * @author bsame
 */
public class Settings extends javax.swing.JPanel {
    public static String statusAbsen;
    public static Preferences prefs = Preferences.systemNodeForPackage(Settings.class);

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        // 1. Membuat objek tombol geser secara manual lewat kode
        slidingStatusToggle1 = new SlidingStatusToogle();
        
        // 2. Mengatur ukuran dan posisi tombol (Silakan disesuaikan kalau kurang pas)
        // 2. Mengatur ukuran dan posisi tombol (sesuaikan jika perlu)
        slidingStatusToggle1.setBounds(90, 110, 220, 45);
        this.setLayout(null); // Memaksa layout bebas agar setBounds berfungsi
        this.add(slidingStatusToggle1); // Memasukkan tombol ke dalam panel Settings

        // 3. Menghubungkan tombol dengan fungsi klik
        slidingStatusToggle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlidingStatusToggle1ActionPerformed(evt);
            }
        });

        // 4. Membaca status terakhir dari preferences
        statusAbsen = prefs.get("LAST_STATUS", "Masuk");
        slidingStatusToggle1.setStatusByString(statusAbsen);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SlidingStatusToggle1ActionPerformed(java.awt.event.ActionEvent evt) {
        statusAbsen = slidingStatusToggle1.getStatusString();
        prefs.put("LAST_STATUS", statusAbsen);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private SlidingStatusToogle slidingStatusToggle1;
}
